name: Test Rust PortPurge on Unix

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Test:
    runs-on: ubuntu-latest
    working-directory: packages/rust
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: moonrepo/setup-rust@v0

      - name: Run Tests
        run: cargo test
